server:
  port: 8080

spring:
  application:
    name: product-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/micro_service?useSSL=false
    password: Shubhu@242424
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

Zipkin:
  Base-url: http://127.0.0.1:9411//
